### ISSUE TITLE
Bug: GUI Scaling Issues

### ISSUE THREAD

**Issue by InterMet-Admin** [InterMet-Systems/Met-GC#27]
Tested with commit 9f9284e9dd68f7f140ddf38ded254b2223319ab9 "less unfinished".

Reproduce by running at a high screen resolution. Screen resolution used was 3840x2400.

Text in the Met window overruns the edges of the window. See image.

![Image](https://github.com/InterMet-Systems/Met-GC/assets/153136213/1f61f747-a078-49a7-bbe7-2f65abbf6687)

Button also overlaps GUI on 1080p

![Image](https://github.com/InterMet-Systems/Met-GC/assets/153136213/c7a734dc-8875-49ae-8d1d-9a7e59123350)

**Comment by vfasburg** [comment]
Getting the height right on the Met window for a 1080x1920 monitor (with full screen window) proved difficult. In order to prevent overflow of the Toolbar in any possible circumstances (the toolbar has various options depending on program state), I decided to limit the vertical size of the toolbar when the Met window is open. 

That will mean that the toolbar might sometimes resort to scrolling to view all options. Although this is always how the toolbar was set up (a very small window or a state with many toolbar options would already have caused this behavior), it is much more likely now with the Met window. I think this is the best compromise that can be attained within a reasonable amount of development time.

Before: 

![Image](https://github.com/InterMet-Systems/Met-GC/assets/10821147/729758e3-87e0-4558-a64e-2d8c5692fcb4)

Now (with replay overlay showing):

![Image](https://github.com/InterMet-Systems/Met-GC/assets/10821147/e5d9a542-bfe6-48d2-b23d-81647b434400)

Now (without replay overlay. Most common for real users):


![Image](https://github.com/InterMet-Systems/Met-GC/assets/10821147/cc7a82e0-6ab1-414b-8244-0056405568bd)

**Comment by InterMet-Admin** [comment]
Tested in 3840x2400: column headers were significantly misaligned with the matching values. Position them more or less over their respective columns, and double check this for the other resolutions by replaying a flight file.

**Comment by InterMet-Admin** [comment]
Commit 2fe3ceb2b49e0a61d8da16d277a88cbe078f4f89.

Determined as functional in 1920x1080 and 3840x2400. Ready to merge.
